name = "FMIZoo"
uuid = "724179cf-c260-40a9-bd27-cccc6fe2f195"
authors = ["FB <frederic.bruder@uni-a.de>", "TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "0.1.0"

[deps]
FilePaths = "8fc22ac5-c921-52a6-82fd-178b2807b824"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1"
FilePaths = "0.8.3"
FilePathsBase = "0.9.17"
Glob = "1.3.0"
Requires = "1.3.0"
