name = "FMIZoo"
uuid = "724179cf-c260-40a9-bd27-cccc6fe2f195"
authors = ["FB <frederic.bruder@uni-a.de>", "TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "1.2.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FilePaths = "8fc22ac5-c921-52a6-82fd-178b2807b824"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[weakdeps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FMI = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"

[extensions]
DifferentialEquationsFMIExt = ["DifferentialEquations", "FMI"]

[compat]
Downloads = "1"
FilePaths = "0.8"
FilePathsBase = "0.9"
Glob = "1.3"
Interpolations = "0.15"
MAT = "0.10"
Optim = "1.9"
PackageExtensionCompat = "1.0.0"
Requires = "1.3"
ZipFile = "0.10.0"
julia = "1.6"
